config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :entries
      resources :organisms
      resources :users
      resources :sessions

      get "/organisms/get_by_user/:id", to: "organisms#get_by_user"

      get "/entries/get_by_organism/:id", to: "entries#get_by_organism"
      # Route for login after signup
      post "/login", to: "sessions#create"
      delete "/logout", to: "sessions#destroy"

      # Route for signing up/creating new user
      post "/signup", to: "users#create"
      get "/me", to: "users#show"
    end
  end

  # Defines the root path route ("/")
  root "home#index"

  get "*path", to: "home#index"
end

app/models/organism.rb
class Organism < ApplicationRecord
    belongs_to :user
    has_many :entries, dependent: :destroy

    has_one_attached :featured_image

    validates :name, :species, :user_id, presence: true
end

app/controllers/api/v1/organisms_controller.rb
class Api::V1::OrganismsController < ApplicationController
  # before_action :set_organism, only: %i[ show edit update destroy ]

  # GET /organisms or /organisms.json
  def index
    organisms = Organism.all
    render json: organisms, status: :ok
  end

  # GET /organisms/1 or /organisms/1.json
  def show
    organism = find_organism
    render json: organism, status: :ok
  end

  def get_by_user
    organism = Organism.where(user_id: params[:id]).order(:name)
    render json: organism
  end

  # POST /organisms or /organisms.json
  def create
    organism = Organism.create!(organism_params)
    render json: organism, status: :created
  end

  # PATCH/PUT /organisms/1 or /organisms/1.json
  def update
    organism = find_organism
    organism.update!(organism_params)
    render json: organism
  end

  # DELETE /organisms/1 or /organisms/1.json
  def destroy
    organism = find_organism
    organism.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_organism
      Organism.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organism_params
      params.permit(:name, :species, :user_id, :featured_image)
    end
end

app/controllers/organisms_controller.rb
class OrganismsController < ApplicationController
  before_action :set_organism, only: %i[ show edit update destroy ]

  # GET /organisms or /organisms.json
  def index
    @organisms = Organism.all
  end

  # GET /organisms/1 or /organisms/1.json
  def show
  end

  # GET /organisms/new
  def new
    @organism = Organism.new
  end

  # GET /organisms/1/edit
  def edit
  end

  # POST /organisms or /organisms.json
  def create
    @organism = Organism.new(organism_params)

    respond_to do |format|
      if @organism.save
        format.html { redirect_to organism_url(@organism), notice: "Organism was successfully created." }
        format.json { render :show, status: :created, location: @organism }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organisms/1 or /organisms/1.json
  def update
    respond_to do |format|
      if @organism.update(organism_params)
        format.html { redirect_to organism_url(@organism), notice: "Organism was successfully updated." }
        format.json { render :show, status: :ok, location: @organism }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organism.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organisms/1 or /organisms/1.json
  def destroy
    @organism.destroy

    respond_to do |format|
      format.html { redirect_to organisms_url, notice: "Organism was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organism
      @organism = Organism.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organism_params
      params.require(:organism).permit(:name, :species, :user_id)
    end
end

app/helpers/organisms_helper.rb
module OrganismsHelper
end

app/views/organisms/_form.html.erb
<%= form_with(model: organism) do |form| %>
  <% if organism.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(organism.errors.count, "error") %> prohibited this organism from being saved:</h2>

      <ul>
        <% organism.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :species, style: "display: block" %>
    <%= form.text_field :species %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/organisms/_organism.html.erb
<div id="<%= dom_id organism %>">
  <p>
    <strong>Name:</strong>
    <%= organism.name %>
  </p>

  <p>
    <strong>Species:</strong>
    <%= organism.species %>
  </p>

  <p>
    <strong>User:</strong>
    <%= organism.user_id %>
  </p>

</div>

app/views/organisms/edit.html.erb
<h1>Editing organism</h1>

<%= render "form", organism: @organism %>

<br>

<div>
  <%= link_to "Show this organism", @organism %> |
  <%= link_to "Back to organisms", organisms_path %>
</div>

app/views/organisms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Organisms</h1>

<div id="organisms">
  <% @organisms.each do |organism| %>
    <%= render organism %>
    <p>
      <%= link_to "Show this organism", organism %>
    </p>
  <% end %>
</div>

<%= link_to "New organism", new_organism_path %>

app/views/organisms/new.html.erb
<h1>New organism</h1>

<%= render "form", organism: @organism %>

<br>

<div>
  <%= link_to "Back to organisms", organisms_path %>
</div>

app/views/organisms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @organism %>

<div>
  <%= link_to "Edit this organism", edit_organism_path(@organism) %> |
  <%= link_to "Back to organisms", organisms_path %>

  <%= button_to "Destroy this organism", @organism, method: :delete %>
</div>