config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :entries
      resources :organisms
      resources :users
      resources :sessions

      get "/organisms/get_by_user/:id", to: "organisms#get_by_user"

      get "/entries/get_by_organism/:id", to: "entries#get_by_organism"
      # Route for login after signup
      post "/login", to: "sessions#create"
      delete "/logout", to: "sessions#destroy"

      # Route for signing up/creating new user
      post "/signup", to: "users#create"
      get "/me", to: "users#show"
    end
  end

  # Defines the root path route ("/")
  root "home#index"

  get "*path", to: "home#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :organism

    has_one_attached :entry_image

    validates :note, :date, :organism_id, presence: true
end

app/controllers/api/v1/entries_controller.rb
class Api::V1::EntriesController < ApplicationController
  # before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    entries = Entry.all
    render json: entries, status: :ok
  end

  # GET /entries/1 or /entries/1.json
  def show
    entry = find_entry
    render json: entry, status: :ok
  end

  def get_by_organism
    entry = Entry.where(organism_id: params[:id]).order(:date)
    render json: entry
  end

  # POST /entries or /entries.json
  def create
    entry = Entry.create!(entry_params)
    render json: entry, status: :created
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    entry = find_entry
    entry.update!(entry_params)
    render json: entry
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    entry = find_entry
    entry.destroy
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def find_entry
      Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.permit(:note, :date, :organism_id, :entry_image)
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:note, :date, :organism_id)
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Note:</strong>
    <%= entry.note %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= entry.date %>
  </p>

  <p>
    <strong>Organism:</strong>
    <%= entry.organism_id %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :note, style: "display: block" %>
    <%= form.text_field :note %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>

  <div>
    <%= form.label :organism_id, style: "display: block" %>
    <%= form.number_field :organism_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entries</h1>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
    <p>
      <%= link_to "Show this entry", entry %>
    </p>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path %>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>